FROM nvidia/cuda:12.1-runtime-ubuntu22.04

WORKDIR /app

# Copier le fichier requirements.txt
COPY requirements.txt .

# Créer un environnement virtuel et installer les dépendances
RUN python -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir -r requirements.txt


RUN /app/venv/bin/pip install torch==2.5.1+cu121 torchvision==0.20.1+cu121 torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 9200

# Activer le venv et lancer l'application
CMD ["/app/venv/bin/uvicorn", "medium.py:app", "--host", "0.0.0.0", "--port", "9200"]
